---
ntp_timezone: America/Boston

java_packages:
  - java-1.8.0-openjdk

jenkins_plugins:
  - ant
  - apache-httpcomponents-client-4-api
  - credentials
  - credentials-binding
  - display-url-api
  - workflow-scm-step
  - git-client
  - git
  - job-dsl
  - jsch
  - junit
  - mailer
  - matrix-project
  - plain-credentials
  - scm-api
  - script-security
  - ssh-credentials
  - structs
  - workflow-step-api
  
jenkins_plugins_state: latest
  
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8080"
